# Generated by Django 4.1.1 on 2023-01-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=60)),
                ('bank_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=10)),
                ('account_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
