# Generated by Django 4.1.1 on 2023-01-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_pic',
            field=models.ImageField(default='', upload_to='seller/'),
            preserve_default=False,
        ),
    ]
