# Generated by Django 4.1.1 on 2023-01-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_seller_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('product_no', models.BigIntegerField()),
                ('product_description', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
            options={
                'db_table': 'product_tb',
            },
        ),
    ]
